// Copyright 2026 The Mwc developers
// Distributed under the CC0 public domain dedication. See LICENSE.

//! Sign-to-contract commitments in ordinary single-signer MWC AggSig signatures.
//!
//! The original signed message, public key, and 64-byte signature format are
//! unchanged. An additional public [`Opening`] lets a verifier check that the
//! signature commits to a caller-supplied 32-byte digest. This is MWC AggSig,
//! not ECDSA or BIP340, and is not a multiparty signing protocol.
//!
//! # Version 1 transcript
//!
//! Let `x` be the signing key, `P = x*G`, `m` the original 32-byte message,
//! and `D` the 32-byte data digest. The secret base nonce `r` is generated by
//! this library's existing RFC6979 function using `key32 = x`, `msg32 = m`,
//! `data32 = D`, and `algo16 = b"MWC-S2C-NONCE-V1"`. Its seed is exactly
//! `x || m || D || algo16`; candidates start at RFC6979 counter zero.
//!
//! For the opening `R0 = r*G`, the public tweak is the first SHA256 result in
//! `1..n` (exclusive of the curve order `n`) from:
//!
//! ```text
//! b"MWC-S2C-TWEAK-V1" || compressed(R0) || compressed(P) || m || D || counter_be32
//! ```
//!
//! Both points use canonical 33-byte SEC1 encoding. All other fields have
//! fixed widths; the tweak counter starts at zero. Each candidate is read as
//! a big-endian integer, rejecting zero and values >= n, without reduction.
//! Sign normally with the nonce `k = r + t (mod n)`. Retry with the next base
//! nonce if `r` is invalid, `k` is zero, or the final signature is unusable.
//! Both candidate searches are bounded at 1024 attempts.
//!
//! Verification first checks the ordinary AggSig signature, then checks that
//! `x(R0 + t*G)` equals its raw nonce x-coordinate. Comparing x-coordinates is
//! intentional: AggSig normalizes its nonce to quadratic-residue Y, which can
//! negate `k*G`. The ordinary verifier enforces that existing convention.
//!
//! # Security and integration
//!
//! The base nonce includes `D`; changing only the public tweak while reusing
//! the base nonce would expose the signing key. The opening is a public curve
//! point, never the secret nonce scalar. Hashing the opening into the tweak is
//! essential to prevent an attacker from algebraically changing the opening.
//!
//! Callers must define what their digest commits to (including version,
//! application/network context, and canonical data encoding). The data is not
//! stored in or recoverable from the signature. Applications must transport
//! the opening and require its verification where binding is mandatory; a
//! missing opening must not silently fall back to ordinary verification.
//! These primitives do not activate blockchain consensus rules. Their exact
//! use in consensus and any multiparty extension require separate review.

use crate::{
    aggsig, constants, ffi, AggSigSignature, Error, Message, PublicKey, Secp256k1, SecretKey,
};
use sha2::{Digest, Sha256};
use zeroize::Zeroizing;

const NONCE_DOMAIN: &[u8; 16] = b"MWC-S2C-NONCE-V1";
const TWEAK_DOMAIN: &[u8] = b"MWC-S2C-TWEAK-V1";
const MAX_ATTEMPTS: u32 = 1024;

/// Public S2C opening, encoded as one canonical compressed SEC1 point.
///
/// This is the base nonce *point* `R0`, not its secret scalar. It is safe to
/// serialize and distribute alongside the signature and committed data.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Opening([u8; constants::COMPRESSED_PUBLIC_KEY_SIZE]);

impl Opening {
    /// Parse exactly 33 bytes containing a valid compressed SEC1 point.
    ///
    /// Rejects uncompressed, hybrid, infinity, and invalid point encodings.
    pub fn from_slice(secp: &Secp256k1, bytes: &[u8]) -> Result<Self, Error> {
        if bytes.len() != constants::COMPRESSED_PUBLIC_KEY_SIZE {
            return Err(Error::InvalidPublicKey);
        }
        PublicKey::from_slice(secp, bytes)?;
        let mut encoded = [0u8; constants::COMPRESSED_PUBLIC_KEY_SIZE];
        encoded.copy_from_slice(bytes);
        Ok(Self(encoded))
    }

    /// Return the canonical 33-byte public opening for storage or transport.
    pub fn serialize(&self) -> [u8; constants::COMPRESSED_PUBLIC_KEY_SIZE] {
        self.0
    }
}

/// Create an ordinary single-signer AggSig signature committing to `data`.
///
/// `msg` remains the original signed message; `data` is an additional 32-byte
/// digest. The public key and secret nonce are derived internally. Identical
/// key/message/data requests produce identical signatures and openings.
/// Changing the message or digest changes the secret base nonce as well.
///
/// Requires a signing-capable context. This intentionally exposes no custom
/// nonce, partial-signature, or aggregate-key options: it is not a multiparty
/// S2C API. The returned signature is accepted by [`aggsig::verify_single`]
/// and [`aggsig::verify_batch`] without supplying the opening or `data`.
pub fn sign_single(
    secp: &Secp256k1,
    msg: &Message,
    key: &SecretKey,
    data: &[u8; 32],
) -> Result<(AggSigSignature, Opening), Error> {
    let public_key = PublicKey::from_secret_key(secp, key)?;
    let public_key_bytes = public_key.serialize_vec(secp, true)?;

    for attempt in 0..MAX_ATTEMPTS {
        let mut nonce = match base_nonce(secp, msg, key, data, attempt) {
            Ok(nonce) => nonce,
            Err(Error::InvalidSecretKey) | Err(Error::ZeroSecretKey) => continue,
            Err(error) => return Err(error),
        };
        let point = PublicKey::from_secret_key(secp, &nonce)?;
        let opening = Opening::from_slice(secp, &point.serialize_vec(secp, true)?)?;
        let tweak = commitment_tweak(secp, &opening, &public_key_bytes, msg, data)?;
        // Add r + t using the library's secret-key scalar operation.
        // PublicKey::add_exp_assign is variable-time and must not receive r
        // as its tweak argument. It is safe for the public tweak t.
        if nonce.add_assign(secp, &tweak).is_err() {
            continue; // r + t == 0. The next attempt also changes the opening.
        }
        match aggsig::sign_single(secp, msg, key, Some(&nonce), None, None, &public_key, None) {
            Ok(signature) => return Ok((signature, opening)),
            Err(Error::InvalidSignature) => continue,
            Err(error) => return Err(error),
        }
    }
    Err(Error::NonceExportError)
}

/// Verify both an ordinary AggSig signature and its S2C commitment to `data`.
///
/// Returns `Ok(false)` for an invalid signature, public key, or commitment.
/// A context without verification capability returns an error. Always checks
/// the full ordinary signature, not just the public nonce commitment.
/// Exhausting all tweak candidates or an internal serialization failure also
/// returns an error; neither outcome permits accepting the signature.
pub fn verify_single(
    secp: &Secp256k1,
    signature: &AggSigSignature,
    msg: &Message,
    public_key: &PublicKey,
    data: &[u8; 32],
    opening: &Opening,
) -> Result<bool, Error> {
    if !aggsig::verify_single(
        secp, signature, msg, None, public_key, public_key, None, false,
    )? {
        return Ok(false);
    }
    let mut point = match PublicKey::from_slice(secp, &opening.0) {
        Ok(point) => point,
        Err(_) => return Ok(false),
    };
    let public_key_bytes = public_key.serialize_vec(secp, true)?;
    let tweak = commitment_tweak(secp, opening, &public_key_bytes, msg, data)?;
    // This tweak is public, so the existing variable-time point operation is
    // appropriate. It also rejects a resulting point at infinity.
    if point.add_exp_assign(secp, &tweak).is_err() {
        return Ok(false);
    }
    let expected_nonce = point.serialize_vec(secp, true)?;
    let raw_signature = signature.to_raw_data(secp)?;
    // AggSig's raw encoding is R.x || s. Its legacy ECDSA compact serializer
    // must not be used here. Ordinary verification above handles the Y sign.
    Ok(expected_nonce[1..] == raw_signature[..32])
}

fn base_nonce(
    secp: &Secp256k1,
    msg: &Message,
    key: &SecretKey,
    data: &[u8; 32],
    attempt: u32,
) -> Result<SecretKey, Error> {
    let mut bytes = Zeroizing::new([0u8; 32]);
    // The existing C API types additional data as mutable, but this nonce
    // function only reads it. Use a local copy to avoid casting away const.
    let mut additional_data = *data;
    // SAFETY: all buffers have the function's required fixed lengths and
    // remain live for this call. The attempt is bounded below MAX_ATTEMPTS,
    // avoiding overflow in the C implementation's inclusive counter loop.
    let result = unsafe {
        ffi::secp256k1_nonce_function_rfc6979(
            bytes.as_mut_ptr(),
            msg.as_ptr(),
            key.as_ptr(),
            NONCE_DOMAIN.as_ptr(),
            additional_data.as_mut_ptr().cast(),
            attempt,
        )
    };
    if result != 1 {
        return Err(Error::NonceExportError);
    }
    // The buffer is wiped on every exit. SecretKey itself zeroizes on drop;
    // the RFC6979 implementation clears its internal key and HMAC state.
    SecretKey::from_slice(secp, bytes.as_ref())
}

fn commitment_tweak(
    secp: &Secp256k1,
    opening: &Opening,
    public_key: &[u8],
    msg: &Message,
    data: &[u8; 32],
) -> Result<SecretKey, Error> {
    for counter in 0..MAX_ATTEMPTS {
        let mut hash = Sha256::new();
        hash.update(TWEAK_DOMAIN);
        hash.update(opening.0);
        hash.update(public_key);
        hash.update(&msg[..]);
        hash.update(data);
        hash.update(counter.to_be_bytes());
        if let Ok(tweak) = SecretKey::from_slice(secp, &hash.finalize()) {
            return Ok(tweak);
        }
    }
    Err(Error::InvalidParameters)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ContextFlag;

    fn key(secp: &Secp256k1, value: u8) -> SecretKey {
        let mut bytes = [0u8; 32];
        bytes[31] = value;
        SecretKey::from_slice(secp, &bytes).unwrap()
    }

    fn message() -> Message {
        Message::from_slice(&[0x42; 32]).unwrap()
    }

    #[test]
    fn independent_vectors_cover_both_nonce_normalizations() {
        // Independently calculated with Python hashlib/hmac and affine
        // secp256k1 arithmetic, without calling this crate or its C library.
        // The first k*G has non-quadratic Y and must be negated by AggSig;
        // the second already has quadratic Y and must remain unchanged.
        let vectors = [
            (
                0x11,
                "0217cbf31493feaa218ac8b45a30918305dcc6931233f030ef4e5495726af0df25",
                concat!(
                    "46d6ff3fceb99ea3750dff82adbaf0d877fdd2c9c56a9405fae4409eeda0e79a",
                    "448bc3356e7f265d949def6137a7c2efda7379a2b8573fa29e50c85cdfbbd1a0",
                ),
            ),
            (
                0x44,
                "03abcb1f2bb4dc8ff29d58ef7a17ae8988de79e8aad4e9b076e9f49dde95c04d69",
                concat!(
                    "de1ae530396ceed2e27bbeb5f92cd9ad33d1994c2ddad738b014b03fd985afbe",
                    "6e2314c8b1991327fd1568b759481441abab0673c104fbba3e5de4e7d4ae760b",
                ),
            ),
        ];
        let hex = |bytes: &[u8]| {
            bytes
                .iter()
                .map(|byte| format!("{:02x}", byte))
                .collect::<String>()
        };
        let secp = Secp256k1::new().unwrap();
        let secret = key(&secp, 1);
        let public_key = PublicKey::from_secret_key(&secp, &secret).unwrap();
        for (value, expected_opening, expected_signature) in vectors {
            let (signature, opening) =
                sign_single(&secp, &message(), &secret, &[value; 32]).unwrap();
            assert_eq!(hex(&opening.serialize()), expected_opening);
            assert_eq!(
                hex(&signature.to_raw_data(&secp).unwrap()),
                expected_signature
            );
            assert!(verify_single(
                &secp,
                &signature,
                &message(),
                &public_key,
                &[value; 32],
                &opening,
            )
            .unwrap());
        }
    }

    #[test]
    fn kernel_excess_signature_passes_existing_verifiers() {
        let secp = Secp256k1::with_caps(ContextFlag::Commit).unwrap();
        let blind = key(&secp, 7);
        let reward = 60_000_000_000;
        let output = secp.commit(reward, blind.clone()).unwrap();
        let overage = secp.commit_value(reward).unwrap();
        let excess = secp.commit_sum(vec![output], vec![overage]).unwrap();
        let public_key = excess.to_pubkey(&secp).unwrap();
        let msg = message(); // A fixed kernel-style message independent of D.
        let data = [0x11; 32];

        let (signature, opening) = sign_single(&secp, &msg, &blind, &data).unwrap();
        assert!(aggsig::verify_single(
            &secp,
            &signature,
            &msg,
            None,
            &public_key,
            &public_key,
            None,
            false,
        )
        .unwrap());
        assert!(
            aggsig::verify_batch(&secp, &vec![signature], &vec![msg], &vec![public_key],).unwrap()
        );
        assert!(verify_single(&secp, &signature, &msg, &public_key, &data, &opening).unwrap());
        assert!(
            !verify_single(&secp, &signature, &msg, &public_key, &[0x12; 32], &opening,).unwrap()
        );

        let restored = Opening::from_slice(&secp, &opening.serialize()).unwrap();
        assert_eq!(restored, opening);
        assert!(verify_single(&secp, &signature, &msg, &public_key, &data, &restored).unwrap());
    }

    #[test]
    fn repeated_key_changes_base_nonce_for_each_digest_and_message() {
        let secp = Secp256k1::new().unwrap();
        let secret = key(&secp, 9);
        let public_key = PublicKey::from_secret_key(&secp, &secret).unwrap();
        let msg = message();
        let mut signatures = Vec::new();
        let mut openings = Vec::new();
        for value in 0..8 {
            let data = [value; 32];
            let (signature, opening) = sign_single(&secp, &msg, &secret, &data).unwrap();
            assert!(verify_single(&secp, &signature, &msg, &public_key, &data, &opening).unwrap());
            // Changing only the tweaked nonce is insufficient: the base
            // nonce point must change too, or related signatures leak x.
            assert!(!openings.contains(&opening));
            assert!(!signatures.contains(&signature));
            for previous in &openings {
                assert!(
                    !verify_single(&secp, &signature, &msg, &public_key, &data, previous,).unwrap()
                );
            }
            let repeated = sign_single(&secp, &msg, &secret, &data).unwrap();
            assert_eq!(repeated, (signature, opening));
            signatures.push(signature);
            openings.push(opening);
        }
        assert!(aggsig::verify_batch(
            &secp,
            &signatures,
            &vec![msg; signatures.len()],
            &vec![public_key; signatures.len()],
        )
        .unwrap());
        let changed_message = Message::from_slice(&[0x43; 32]).unwrap();
        let (_, changed_opening) = sign_single(&secp, &changed_message, &secret, &[0; 32]).unwrap();
        assert_ne!(changed_opening, openings[0]);
    }

    #[test]
    fn rejects_altered_opening_key_message_and_signature() {
        let secp = Secp256k1::new().unwrap();
        let secret = key(&secp, 3);
        let public_key = PublicKey::from_secret_key(&secp, &secret).unwrap();
        let msg = message();
        let data = [0x44; 32];
        let (signature, opening) = sign_single(&secp, &msg, &secret, &data).unwrap();
        let other_public_key = PublicKey::from_secret_key(&secp, &key(&secp, 4)).unwrap();
        assert!(
            !verify_single(&secp, &signature, &msg, &other_public_key, &data, &opening,).unwrap()
        );
        assert!(!verify_single(
            &secp,
            &signature,
            &Message::from_slice(&[0x43; 32]).unwrap(),
            &public_key,
            &data,
            &opening,
        )
        .unwrap());

        // The complete compressed opening, including its sign bit, is bound.
        let mut negated = opening.serialize();
        negated[0] ^= 1;
        let negated = Opening::from_slice(&secp, &negated).unwrap();
        assert!(!verify_single(&secp, &signature, &msg, &public_key, &data, &negated).unwrap());

        // Keep R.x unchanged. A nonce-only commitment check would accept
        // this, but full verification must reject the changed signature s.
        let mut raw = signature.to_raw_data(&secp).unwrap();
        raw[32..].copy_from_slice(&key(&secp, 1)[..]);
        let invalid = AggSigSignature::from_raw_data(&secp, &raw).unwrap();
        assert!(!verify_single(&secp, &invalid, &msg, &public_key, &data, &opening).unwrap());
        assert!(!verify_single(
            &secp,
            &AggSigSignature::new(),
            &msg,
            &public_key,
            &data,
            &opening,
        )
        .unwrap());

        let ordinary =
            aggsig::sign_single(&secp, &msg, &secret, None, None, None, &public_key, None).unwrap();
        assert!(aggsig::verify_single(
            &secp,
            &ordinary,
            &msg,
            None,
            &public_key,
            &public_key,
            None,
            false,
        )
        .unwrap());
        assert!(!verify_single(&secp, &ordinary, &msg, &public_key, &data, &opening).unwrap());
    }

    #[test]
    fn opening_rejects_noncanonical_and_invalid_points() {
        let secp = Secp256k1::new().unwrap();
        let point = PublicKey::from_secret_key(&secp, &key(&secp, 1)).unwrap();
        let compressed = point.serialize_vec(&secp, true).unwrap();
        assert!(Opening::from_slice(&secp, &compressed).is_ok());
        for length in [0, 1, 32, 34, 65] {
            assert!(Opening::from_slice(&secp, &vec![0; length]).is_err());
        }
        assert!(Opening::from_slice(&secp, &point.serialize_vec(&secp, false).unwrap()).is_err());
        for prefix in [0, 1, 4, 6, 7, 255] {
            let mut bytes = [0u8; 33];
            bytes.copy_from_slice(&compressed);
            bytes[0] = prefix;
            assert!(Opening::from_slice(&secp, &bytes).is_err());
        }
        let mut no_point = [0u8; 33]; // x=0 does not lift to a secp256k1 point.
        no_point[0] = 2;
        assert!(Opening::from_slice(&secp, &no_point).is_err());
        let mut out_of_field = [0xff; 33];
        out_of_field[0] = 2;
        assert!(Opening::from_slice(&secp, &out_of_field).is_err());
    }

    #[test]
    fn signing_and_verification_contexts_are_separate() {
        let signing = Secp256k1::with_caps(ContextFlag::SignOnly).unwrap();
        let verifying = Secp256k1::with_caps(ContextFlag::VerifyOnly).unwrap();
        let none = Secp256k1::with_caps(ContextFlag::None).unwrap();
        let secret = key(&signing, 2);
        let public_key = PublicKey::from_secret_key(&signing, &secret).unwrap();
        let msg = message();
        let data = [0x55; 32];
        let (signature, opening) = sign_single(&signing, &msg, &secret, &data).unwrap();
        assert!(verify_single(&verifying, &signature, &msg, &public_key, &data, &opening).unwrap());
        for context in [&verifying, &none] {
            assert_eq!(
                sign_single(context, &msg, &secret, &data),
                Err(Error::IncapableContext)
            );
        }
        for context in [&signing, &none] {
            assert_eq!(
                verify_single(context, &signature, &msg, &public_key, &data, &opening),
                Err(Error::IncapableContext),
            );
        }
        assert!(sign_single(&signing, &msg, &SecretKey([0; 32]), &data).is_err());
    }
}
